version: '2'
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
      - ./volumes/ssl:/vault/ssl
      - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-certificates.crt
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config